In [11]:
# Add the Pandas dependency.
import pandas as pd

In [13]:
# Files to load
olympic_data_to_load = "Resources/athlete_events.csv"

In [14]:
# Read the school data file and store it in a Pandas DataFrame.
olympic_data_df = pd.read_csv(olympic_data_to_load)
olympic_data_df

,Name,Sex,Age,Height,Weight,Team,Games,Season,Event,Medal
0,A Dijiang,M,24.0,180.0,80.0,China,1992 Summer,Summer,Basketball Men's Basketball,NaN
1,A Lamusi,M,23.0,170.0,60.0,China,2012 Summer,Summer,Judo Men's Extra-Lightweight,NaN
2,Gunnar Nielsen Aaby,M,24.0,NaN,NaN,Denmark,1920 Summer,Summer,Football Men's Football,NaN
3,Edgar Lindenau Aabye,M,34.0,NaN,NaN,Denmark/Sweden,1900 Summer,Summer,Tug-Of-War Men's Tug-Of-War,Gold
4,Christine Jacoba Aaftink,F,21.0,185.0,82.0,Netherlands,1988 Winter,Winter,Speed Skating Women's 500 metres,NaN
...,...,...,...,...,...,...,...,...,...,...
271111,Andrzej ya,M,29.0,179.0,89.0,Poland-1,1976 Winter,Winter,Luge Mixed (Men)'s Doubles,NaN
271112,Piotr ya,M,27.0,176.0,59.0,Poland,2014 Winter,Winter,"Ski Jumping Men's Large Hill, Individual",NaN
271113,Piotr ya,M,27.0,176.0,59.0,Poland,2014 Winter,Winter,"Ski Jumping Men's Large Hill, Team",NaN
271114,Tomasz Ireneusz ya,M,30.0,185.0,96.0,Poland,1998 Winter,Winter,Bobsleigh Men's Four,NaN
271115,Tomasz Ireneusz ya,M,34.0,185.0,96.0,Poland,2002 Winter,Winter,Bobsleigh Men's Four,NaN

In [15]:
# Determine if there are any missing values in the school data.
olympic_data_df.count()

Name      271116
Sex       271116
Age       261642
Height    210945
Weight    208241
Team      271116
Games     271116
Season    271116
Event     271116
Medal      39783
dtype: int64

In [17]:
# Drop the NaNs.
olympic_data_df.dropna()

,Name,Sex,Age,Height,Weight,Team,Games,Season,Event,Medal
40,Juhamatti Tapio Aaltonen,M,28.0,184.0,85.0,Finland,2014 Winter,Winter,Ice Hockey Men's Ice Hockey,Bronze
41,Paavo Johannes Aaltonen,M,28.0,175.0,64.0,Finland,1948 Summer,Summer,Gymnastics Men's Individual All-Around,Bronze
42,Paavo Johannes Aaltonen,M,28.0,175.0,64.0,Finland,1948 Summer,Summer,Gymnastics Men's Team All-Around,Gold
44,Paavo Johannes Aaltonen,M,28.0,175.0,64.0,Finland,1948 Summer,Summer,Gymnastics Men's Horse Vault,Gold
48,Paavo Johannes Aaltonen,M,28.0,175.0,64.0,Finland,1948 Summer,Summer,Gymnastics Men's Pommelled Horse,Gold
...,...,...,...,...,...,...,...,...,...,...
271078,Galina Ivanovna Zybina (-Fyodorova),F,25.0,168.0,80.0,Soviet Union,1956 Summer,Summer,Athletics Women's Shot Put,Silver
271080,Galina Ivanovna Zybina (-Fyodorova),F,33.0,168.0,80.0,Soviet Union,1964 Summer,Summer,Athletics Women's Shot Put,Bronze
271082,Bogusaw Zych,M,28.0,182.0,82.0,Poland,1980 Summer,Summer,"Fencing Men's Foil, Team",Bronze
271102,Olesya Nikolayevna Zykina,F,19.0,171.0,64.0,Russia,2000 Summer,Summer,Athletics Women's 4 x 400 metres Relay,Bronze
271103,Olesya Nikolayevna Zykina,F,23.0,171.0,64.0,Russia,2004 Summer,Summer,Athletics Women's 4 x 400 metres Relay,Silver